project_id   = "modern-girder-463514-t1"
region       = "us-central1"
zone         = "us-central1-a"
network_name = "custom-vpc"
gke_node_sa_email = "gke-node-sa@modern-girder-463514-t1.iam.gserviceaccount.com "
