name: Terraform Destroy

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    name: Terraform Destroy Job
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: |
          terraform init \
           -backend-config="bucket=${{ secrets.GCS_BUCKET_NAME }}" \
           -backend-config="prefix=gke-secure-app/network"

      - name: Terraform Destroy
        run: |
          terraform -chdir=terraform destroy -auto-approve \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}" \
          -var="zone=${{ secrets.GCP_ZONE }}" \
          -var="network_name=secure-vpc"

