name: Terraform Deploy to GCP (Simple Auth)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply with Simple GCP Auth
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🔧 Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: 🔐 Authenticate with Google Cloud (Service Account Key)
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: ☁️ Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.GCS_BUCKET_NAME }}" \
            -backend-config="prefix=gke-secure-app"
        working-directory: terraform/

      - name: 🚀 Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ secrets.GCP_REGION }}" \
            -var="zone=${{ secrets.GCP_ZONE }}" \
            -var="network_name=secure-vpc"
        working-directory: terraform/

      - name: ✅ Verify Auth
        run: gcloud auth list
