name: Terraform Deploy to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_ZONE: ${{ secrets.GCP_ZONE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${GCS_BUCKET_NAME}" \
            -backend-config="prefix=gke-secure-app/network"
        working-directory: terraform/

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="project_id=${GCP_PROJECT_ID}" \
            -var="region=${GCP_REGION}" \
            -var="zone=${GCP_ZONE}" \
            -var="network_name=secure-vpc"
        working-directory: terraform/

